name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update contributors section in README
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          readme_path: 'README.md'
          use_username: true
          commit_message: 'chore(docs): update contributors section'
          columns_per_row: 6

